"""initial migration

Revision ID: c4ce8422698e
Revises: 
Create Date: 2017-02-16 17:56:27.830000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c4ce8422698e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_permission')
    op.drop_table('books_book_authors')
    op.drop_table('django_admin_log')
    op.drop_table('tb_promo_code')
    op.drop_table('auth_group_permissions')
    op.drop_table('auth_group')
    op.drop_table('tb_orders')
    op.drop_table('books_publisher')
    op.drop_table('auth_user')
    op.drop_table('guest_message_messages')
    op.drop_table('books_author')
    op.drop_table('auth_user_user_permissions')
    op.drop_table('django_migrations')
    op.drop_table('auth_user_groups')
    op.drop_table('django_content_type')
    op.drop_table('django_session')
    op.drop_table('books_book')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books_book',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('publication_date', sa.DATE(), nullable=False),
    sa.Column('publisher_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['publisher_id'], [u'books_publisher.id'], name=u'books_book_publisher_id_77eb31e_fk_books_publisher_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('django_session',
    sa.Column('session_key', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('session_data', mysql.LONGTEXT(), nullable=False),
    sa.Column('expire_date', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('session_key'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('django_content_type',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('app_label', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('model', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('auth_user_groups',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('group_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], [u'auth_group.id'], name=u'auth_user_groups_group_id_15a5f1c6_fk_auth_group_id'),
    sa.ForeignKeyConstraint(['user_id'], [u'auth_user.id'], name=u'auth_user_groups_user_id_3e9d40a8_fk_auth_user_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('django_migrations',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('app', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('applied', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('auth_user_user_permissions',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('permission_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], [u'auth_permission.id'], name=u'auth_user_user_perm_permission_id_28ebfa04_fk_auth_permission_id'),
    sa.ForeignKeyConstraint(['user_id'], [u'auth_user.id'], name=u'auth_user_user_permissions_user_id_3404d403_fk_auth_user_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('books_author',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=254), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('guest_message_messages',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('guest_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('guest_datetime', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('guest_content', mysql.LONGTEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('auth_user',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('last_login', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('is_superuser', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=254), nullable=False),
    sa.Column('is_staff', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('date_joined', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('books_publisher',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('city', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('state_province', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('country', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('website', mysql.VARCHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('tb_orders',
    sa.Column('orderid', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('auth_group',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('auth_group_permissions',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('group_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('permission_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], [u'auth_group.id'], name=u'auth_group_permissions_group_id_2cfd468_fk_auth_group_id'),
    sa.ForeignKeyConstraint(['permission_id'], [u'auth_permission.id'], name=u'auth_group_permissi_permission_id_7e9c51c9_fk_auth_permission_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('tb_promo_code',
    sa.Column('id', mysql.BIGINT(display_width=20), nullable=False),
    sa.Column('promo_code', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('use_type', mysql.TINYINT(display_width=4), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('django_admin_log',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('action_time', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('object_id', mysql.LONGTEXT(), nullable=True),
    sa.Column('object_repr', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('action_flag', mysql.SMALLINT(display_width=5, unsigned=True), autoincrement=False, nullable=False),
    sa.Column('change_message', mysql.LONGTEXT(), nullable=False),
    sa.Column('content_type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], [u'django_content_type.id'], name=u'django_admin__content_type_id_63dabb48_fk_django_content_type_id'),
    sa.ForeignKeyConstraint(['user_id'], [u'auth_user.id'], name=u'django_admin_log_user_id_f67000f_fk_auth_user_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('books_book_authors',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('book_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('author_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], [u'books_author.id'], name=u'books_book_authors_author_id_7ee7e63a_fk_books_author_id'),
    sa.ForeignKeyConstraint(['book_id'], [u'books_book.id'], name=u'books_book_authors_book_id_7e6211d3_fk_books_book_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('auth_permission',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('content_type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('codename', mysql.VARCHAR(length=100), nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], [u'django_content_type.id'], name=u'auth_permissi_content_type_id_67e8a3bb_fk_django_content_type_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    # ### end Alembic commands ###
